#! /usr/bin/env guile
!#
;;; ravanan --- High-reproducibility CWL runner powered by Guix
;;; Copyright © 2024 Arun Isaac <arunisaac@systemreboot.net>
;;;
;;; This file is part of ravanan.
;;;
;;; ravanan is free software: you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by
;;; the Free Software Foundation, either version 3 of the License, or
;;; (at your option) any later version.
;;;
;;; ravanan is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;; General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with ravanan.  If not, see <https://www.gnu.org/licenses/>.

(use-modules (ice-9 match))

(define (prepend-path-env! name . values)
  (setenv name (string-join (append values
                                    (if (getenv name)
                                        (string-split (getenv name) #\:)
                                        '()))
                            ":")))

(define %source-dir (dirname (current-filename)))

(prepend-path-env! "GUILE_LOAD_PATH" %source-dir)
(prepend-path-env! "GUILE_LOAD_COMPILED_PATH" %source-dir)
(prepend-path-env! "PATH" (string-append %source-dir "/bin"))

(match (command-line)
  ((_ command args ...)
   (apply execlp command command args)))
